### ISSUE TITLE
The code is missing :)

### ISSUE THREAD

**Issue by ericmccullough** [Project-Prismatica/Prismatica#1]
Just watched the webcast.  It sounds very cool.  Any idea of when you will push the code?

**Comment by 0sm0s1z** [comment]
While it's extremely beta, undocumented, and doesn't have a release or distribution just yet..... I did share the code. Check out the main repo here: https://github.com/Project-Prismatica

Prismatica is a grouping of applications. Right now the apps in dev are: Emergence, Oculus, Diagon, and the Prism Shell (GUI).

I'm hoping to have a real release out in the first couple weeks of March.

**Comment by ericmccullough** [comment]
Oops!  Looked in the wrong place.  Thanks!

I know the feeling of wanting to get a project out but also wanting it to be at some reasonable level of functionality et. al.

EricM

________________________________
